with open("Hari_2/file/data.txt", "w") as file:
    file.write("Baris 1\n")
    file.write("Baris 2\n")
    file.write("Baris 3\n")
    file.write("Baris 4\n")
    file.write("Baris 5\n")
    file.write("Baris 6\n")
    file.write("Baris 7\n")
    file.write("Baris 8\n")
    file.write("Baris 9\n")
    file.write("Baris 10\n")